package constantes

const (
	POURCENTAGE_AGRESSEUR_F = .02  // ...
	POURCENTAGE_AGRESSEUR_H = .125 // ...
	GEN_F_H_CANDIDATS       = .5   // ...
	ANCIENNETE_MAX          = 40   // ...
	SANTE_MENTALE_MAX       = 100  // ...
	DEGATS_TRAUMATISME      = 10   // ...
	COMPETENCE_MIN          = 0
	COMPETENCE_MAX          = 10
	POURCENTAGE_RECRUTEMENT = .05
	NB_CANDIDATS_PAR_OFFRE  = 18 // Source : https://blog.flatchr.io/barometre-des-entreprises-qui-recrutent-deuxieme-semestre-2022
)
