package constantes

const (
	POURCENTAGE_AGRESSEUR   = .5  // ...
	ANCIENNETE_MAX_INT      = 30  // ...
	POURCENTAGE_AGRESSION_F = .12 // ...
	POURCENTAGE_AGRESSION_H = .02 // ...
	GEN_F_H_CANDIDATS       = .5  // ...
	ANCIENNETE_MAX          = 40  // ...
	SANTE_MENTALE_MAX       = 100 // ...
	DEGATS_TRAUMATISME      = 10  // ...
	NB_MAX_VSS              = 5   // ...
)
